# Base configs
baseurl: /astral

# UI configs
title: "naik vishw"
name: "naik vishw"
bio: "A programmer"
social_urls:
  facebook: "https://www.facebook.com/vishw naik"
  twitter: "https://www.twitter.com/mistryvatsal11"
  instagram: "https://www.instagram.com/vishw naik"
